server:
  port: 9090
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrito_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      indent-output: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    tags:
      application: carrito-saas
  server:
    port: 9090

logging:
  level:
    root: INFO
    com.carrito: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [business:%X{businessId:-}] [user:%X{userId:-}] [corr:%X{correlationId:-}] %-5level %logger{36} - %msg%n"

  file:
    name: logs/app.log	